// SPDX-License-Identifier: MIT
// Part of @cad0p/pi-steering-hooks.

/**
 * Walk-up discovery + merge tests for {@link loadConfigs},
 * {@link buildConfig}, and {@link loadSteeringConfig}.
 *
 * Uses the same scratch-HOME + `mkdtempSync` pattern as the v1 JSON
 * loader tests (`../loader.test.ts`) to keep global config leakage
 * out of the test run. Fixtures are written fresh per test so runs
 * are reproducible without repo-committed scratch files.
 */

import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";
import {
	ancestorChain,
	buildConfig,
	configCandidates,
	findConfigFile,
	loadConfigs,
	loadSteeringConfig,
} from "./loader.ts";
import type { Plugin, SteeringConfig } from "./schema.ts";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Emit a minimal `.ts` config module at `file`. */
function writeConfig(file: string, body: string): void {
	mkdirSync(join(file, ".."), { recursive: true });
	writeFileSync(file, body, "utf8");
}

/**
 * Body template: default-exports an object literal with the given
 * identifiers / patterns. Kept as raw source so the real dynamic-import
 * codepath runs (we're testing the native-TS-loading behavior, not a
 * synthetic hook).
 */
function configModule(body: string): string {
	return `// Generated by loader.test.ts\nexport default ${body};\n`;
}

// ---------------------------------------------------------------------------
// Unit bits
// ---------------------------------------------------------------------------

describe("v2/loader: configCandidates", () => {
	it("returns index.ts before steering.ts", () => {
		const [a, b] = configCandidates("/tmp/x");
		assert.equal(a, "/tmp/x/.pi/steering/index.ts");
		assert.equal(b, "/tmp/x/.pi/steering.ts");
	});
});

describe("v2/loader: ancestorChain", () => {
	it("returns innermost first", () => {
		const prior = process.env["HOME"];
		process.env["HOME"] = "/home/user";
		try {
			const chain = ancestorChain("/home/user/projects/foo/bar");
			assert.deepEqual(chain, [
				"/home/user/projects/foo/bar",
				"/home/user/projects/foo",
				"/home/user/projects",
				"/home/user",
			]);
		} finally {
			if (prior === undefined) delete process.env["HOME"];
			else process.env["HOME"] = prior;
		}
	});

	it("stops at filesystem root if $HOME is unset", () => {
		const prior = process.env["HOME"];
		delete process.env["HOME"];
		try {
			const chain = ancestorChain("/a/b");
			assert.deepEqual(chain, ["/a/b", "/a", "/"]);
		} finally {
			if (prior !== undefined) process.env["HOME"] = prior;
		}
	});
});

// ---------------------------------------------------------------------------
// findConfigFile
// ---------------------------------------------------------------------------

describe("v2/loader: findConfigFile", () => {
	let tmp: string;
	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "pi-steering-v2-loader-"));
	});
	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	it("prefers .pi/steering/index.ts over .pi/steering.ts", () => {
		writeConfig(join(tmp, ".pi", "steering.ts"), configModule("{}"));
		writeConfig(
			join(tmp, ".pi", "steering", "index.ts"),
			configModule("{}"),
		);
		assert.equal(
			findConfigFile(tmp),
			join(tmp, ".pi", "steering", "index.ts"),
		);
	});

	it("falls back to .pi/steering.ts when index.ts is absent", () => {
		writeConfig(join(tmp, ".pi", "steering.ts"), configModule("{}"));
		assert.equal(findConfigFile(tmp), join(tmp, ".pi", "steering.ts"));
	});

	it("returns null when neither candidate exists", () => {
		assert.equal(findConfigFile(tmp), null);
	});
});

// ---------------------------------------------------------------------------
// loadConfigs — walk-up, stray-file warning, bad layer handling
// ---------------------------------------------------------------------------

describe("v2/loader: loadConfigs", () => {
	let tmp: string;
	let priorHome: string | undefined;
	let warnings: string[];
	let origWarn: typeof console.warn;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "pi-steering-v2-loadcfgs-"));
		priorHome = process.env["HOME"];
		process.env["HOME"] = tmp;
		warnings = [];
		origWarn = console.warn;
		console.warn = (msg: unknown) => {
			warnings.push(String(msg));
		};
	});

	afterEach(() => {
		console.warn = origWarn;
		if (priorHome === undefined) delete process.env["HOME"];
		else process.env["HOME"] = priorHome;
		rmSync(tmp, { recursive: true, force: true });
	});

	it("returns empty when no layer has a config", async () => {
		const cwd = join(tmp, "a", "b");
		mkdirSync(cwd, { recursive: true });
		const layers = await loadConfigs(cwd);
		assert.deepEqual(layers, []);
	});

	it("collects ancestor configs inner-first", async () => {
		const outer = join(tmp, "a");
		const inner = join(tmp, "a", "b");
		mkdirSync(inner, { recursive: true });
		writeConfig(
			join(outer, ".pi", "steering.ts"),
			configModule("{ disable: ['outer-only'] }"),
		);
		writeConfig(
			join(inner, ".pi", "steering.ts"),
			configModule("{ disable: ['inner-only'] }"),
		);
		const layers = await loadConfigs(inner);
		// Inner (b) → outer (a) order.
		assert.deepEqual(layers.map((l) => l.disable?.[0]), [
			"inner-only",
			"outer-only",
		]);
	});

	it("prefers index.ts over steering.ts at the same layer", async () => {
		const cwd = join(tmp, "project");
		mkdirSync(cwd, { recursive: true });
		writeConfig(
			join(cwd, ".pi", "steering.ts"),
			configModule("{ disable: ['flat-file'] }"),
		);
		writeConfig(
			join(cwd, ".pi", "steering", "index.ts"),
			configModule("{ disable: ['directory'] }"),
		);
		const layers = await loadConfigs(cwd);
		assert.equal(layers.length, 1);
		assert.deepEqual(layers[0]?.disable, ["directory"]);
	});

	it("warns about non-.ts files under .pi/steering/", async () => {
		const cwd = join(tmp, "project");
		mkdirSync(cwd, { recursive: true });
		// Create the steering/ dir with a stray non-.ts file AND no
		// index.ts, so the loader has a reason to walk the dir.
		mkdirSync(join(cwd, ".pi", "steering"), { recursive: true });
		writeFileSync(
			join(cwd, ".pi", "steering", "rules.mjs"),
			"// not ts",
			"utf8",
		);
		writeFileSync(
			join(cwd, ".pi", "steering", "rules.json"),
			"{}",
			"utf8",
		);
		await loadConfigs(cwd);
		const relevant = warnings.filter((w) =>
			w.includes("ignoring non-.ts file"),
		);
		assert.equal(relevant.length, 2);
		assert.ok(relevant.some((w) => w.endsWith("rules.mjs")));
		assert.ok(relevant.some((w) => w.endsWith("rules.json")));
	});

	it("does NOT warn about .ts helpers under .pi/steering/", async () => {
		const cwd = join(tmp, "project");
		mkdirSync(cwd, { recursive: true });
		writeConfig(
			join(cwd, ".pi", "steering", "index.ts"),
			configModule("{}"),
		);
		writeConfig(
			join(cwd, ".pi", "steering", "helpers.ts"),
			"export const x = 1;",
		);
		await loadConfigs(cwd);
		assert.deepEqual(
			warnings.filter((w) => w.includes("ignoring")),
			[],
		);
	});

	it("logs + skips a layer whose module fails to import", async () => {
		const cwd = join(tmp, "project");
		mkdirSync(cwd, { recursive: true });
		writeConfig(
			join(cwd, ".pi", "steering.ts"),
			"export default { rules: {{ not valid ts }} };",
		);
		const layers = await loadConfigs(cwd);
		assert.deepEqual(layers, []);
		assert.ok(
			warnings.some((w) => w.includes("failed to load config")),
			`expected an import-failure warning, got: ${JSON.stringify(warnings)}`,
		);
	});

	it("logs + skips a module whose default export isn't an object", async () => {
		const cwd = join(tmp, "project");
		mkdirSync(cwd, { recursive: true });
		writeConfig(
			join(cwd, ".pi", "steering.ts"),
			"export default 42;",
		);
		const layers = await loadConfigs(cwd);
		assert.deepEqual(layers, []);
		assert.ok(
			warnings.some((w) =>
				w.includes("must be a SteeringConfig object"),
			),
		);
	});
});

// ---------------------------------------------------------------------------
// buildConfig — merge semantics
// ---------------------------------------------------------------------------

describe("v2/loader: buildConfig", () => {
	let warnings: string[];
	let origWarn: typeof console.warn;

	beforeEach(() => {
		warnings = [];
		origWarn = console.warn;
		console.warn = (msg: unknown) => {
			warnings.push(String(msg));
		};
	});
	afterEach(() => {
		console.warn = origWarn;
	});

	it("concatenates rules from all layers (inner-first)", () => {
		const inner: SteeringConfig = {
			rules: [
				{
					name: "inner",
					tool: "bash",
					field: "command",
					pattern: /^x/,
					reason: "r",
				},
			],
		};
		const outer: SteeringConfig = {
			rules: [
				{
					name: "outer",
					tool: "bash",
					field: "command",
					pattern: /^y/,
					reason: "r",
				},
			],
		};
		const merged = buildConfig([inner, outer]);
		assert.deepEqual(merged.rules?.map((r) => r.name), ["inner", "outer"]);
	});

	it("inner rule by same name overrides outer (and stays silent)", () => {
		const inner: SteeringConfig = {
			rules: [
				{
					name: "dup",
					tool: "bash",
					field: "command",
					pattern: /^INNER/,
					reason: "inner reason",
				},
			],
		};
		const outer: SteeringConfig = {
			rules: [
				{
					name: "dup",
					tool: "bash",
					field: "command",
					pattern: /^OUTER/,
					reason: "outer reason",
				},
			],
		};
		const merged = buildConfig([inner, outer]);
		assert.equal(merged.rules?.length, 1);
		assert.equal(merged.rules?.[0]?.reason, "inner reason");
		// Cross-layer rule overrides are intentional — no warning.
		assert.deepEqual(warnings, []);
	});

	it("unions disable / disablePlugins across layers", () => {
		const inner: SteeringConfig = {
			disable: ["a"],
			disablePlugins: ["pA"],
		};
		const outer: SteeringConfig = {
			disable: ["b", "a"], // dup with inner — should coalesce
			disablePlugins: ["pB"],
		};
		const merged = buildConfig([inner, outer]);
		assert.deepEqual(merged.disable?.sort(), ["a", "b"]);
		assert.deepEqual(merged.disablePlugins?.sort(), ["pA", "pB"]);
	});

	it("inner `defaultNoOverride` wins; missing layer leaves outer in place", () => {
		assert.equal(
			buildConfig([{}, { defaultNoOverride: true }]).defaultNoOverride,
			true,
			"outer sets it, inner doesn't — outer wins",
		);
		assert.equal(
			buildConfig([{ defaultNoOverride: false }, { defaultNoOverride: true }])
				.defaultNoOverride,
			false,
			"inner explicitly false beats outer true",
		);
		assert.equal(buildConfig([]).defaultNoOverride, undefined);
	});

	it("inner `disableDefaults` wins", () => {
		assert.equal(
			buildConfig([
				{ disableDefaults: true },
				{ disableDefaults: false },
			]).disableDefaults,
			true,
		);
		assert.equal(buildConfig([]).disableDefaults, undefined);
	});

	it("concatenates plugins; first-wins on duplicate plugin names", () => {
		const pInner: Plugin = { name: "p", rules: [] };
		const pOuter: Plugin = { name: "p", rules: [] };
		const merged = buildConfig([{ plugins: [pInner] }, { plugins: [pOuter] }]);
		assert.equal(merged.plugins?.length, 1);
		assert.ok(
			warnings.some((w) => w.includes('duplicate plugin "p"')),
			`expected a plugin-collision warning: ${JSON.stringify(warnings)}`,
		);
	});

	it("concatenates observers; soft-warns on within-layer duplicates", () => {
		const merged = buildConfig([
			{
				observers: [
					{ name: "o", onResult: () => {} },
					{ name: "o", onResult: () => {} },
				],
			},
		]);
		assert.equal(merged.observers?.length, 1);
		assert.ok(warnings.some((w) => w.includes('duplicate observer "o"')));
	});

	it("hard-errors on tracker name collision across plugins", () => {
		const t = { initial: 0, unknown: -1, modifiers: {} } as const;
		const a: Plugin = { name: "pa", trackers: { branch: t as never } };
		const b: Plugin = { name: "pb", trackers: { branch: t as never } };
		assert.throws(
			() => buildConfig([{ plugins: [a] }, { plugins: [b] }]),
			/tracker name collision/,
		);
	});

	it("soft-warns on tracker-extension collision", () => {
		const modifier = { scope: "per-command" as const, apply: () => "" };
		const a: Plugin = {
			name: "pa",
			trackerExtensions: { cwd: { git: modifier as never } },
		};
		const b: Plugin = {
			name: "pb",
			trackerExtensions: { cwd: { git: modifier as never } },
		};
		buildConfig([{ plugins: [a] }, { plugins: [b] }]);
		assert.ok(
			warnings.some((w) =>
				w.includes("duplicate tracker extension") && w.includes("cwd/git"),
			),
			`expected tracker-ext collision warning: ${JSON.stringify(warnings)}`,
		);
	});

	it("soft-warns on predicate key collision", () => {
		const handler = (_a: unknown, _c: unknown) => true;
		const a: Plugin = {
			name: "pa",
			predicates: { branch: handler as never },
		};
		const b: Plugin = {
			name: "pb",
			predicates: { branch: handler as never },
		};
		buildConfig([{ plugins: [a] }, { plugins: [b] }]);
		assert.ok(
			warnings.some((w) => w.includes("duplicate predicate")),
		);
	});

	it("applies `defaults` as the outermost layer", () => {
		const merged = buildConfig(
			[{ rules: [{ name: "user", tool: "bash", field: "command", pattern: /u/, reason: "u" }] }],
			{
				rules: [
					{
						name: "built-in",
						tool: "bash",
						field: "command",
						pattern: /b/,
						reason: "b",
					},
				],
				defaultNoOverride: true,
			},
		);
		assert.deepEqual(
			merged.rules?.map((r) => r.name).sort(),
			["built-in", "user"],
		);
		assert.equal(merged.defaultNoOverride, true);
	});

	it("user rule shadows a defaults rule of the same name", () => {
		const merged = buildConfig(
			[
				{
					rules: [
						{
							name: "shared",
							tool: "bash",
							field: "command",
							pattern: /USER/,
							reason: "user",
						},
					],
				},
			],
			{
				rules: [
					{
						name: "shared",
						tool: "bash",
						field: "command",
						pattern: /DEFAULT/,
						reason: "default",
					},
				],
			},
		);
		assert.equal(merged.rules?.length, 1);
		assert.equal(merged.rules?.[0]?.reason, "user");
	});
});

// ---------------------------------------------------------------------------
// loadSteeringConfig — end-to-end
// ---------------------------------------------------------------------------

describe("v2/loader: loadSteeringConfig", () => {
	let tmp: string;
	let priorHome: string | undefined;
	let origWarn: typeof console.warn;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "pi-steering-v2-end2end-"));
		priorHome = process.env["HOME"];
		process.env["HOME"] = tmp;
		origWarn = console.warn;
		console.warn = () => {};
	});
	afterEach(() => {
		console.warn = origWarn;
		if (priorHome === undefined) delete process.env["HOME"];
		else process.env["HOME"] = priorHome;
		rmSync(tmp, { recursive: true, force: true });
	});

	it("loads + merges a single-layer project", async () => {
		const cwd = join(tmp, "p");
		mkdirSync(cwd, { recursive: true });
		writeConfig(
			join(cwd, ".pi", "steering.ts"),
			configModule(
				`{ rules: [{ name: "r", tool: "bash", field: "command", pattern: "^git", reason: "r" }] }`,
			),
		);
		const merged = await loadSteeringConfig(cwd);
		assert.equal(merged.rules?.length, 1);
		assert.equal(merged.rules?.[0]?.name, "r");
	});

	it("applies caller-supplied defaults when no layer sets a field", async () => {
		const cwd = join(tmp, "p");
		mkdirSync(cwd, { recursive: true });
		const merged = await loadSteeringConfig(cwd, {
			defaultNoOverride: true,
			rules: [
				{
					name: "built-in",
					tool: "bash",
					field: "command",
					pattern: /b/,
					reason: "b",
				},
			],
		});
		assert.equal(merged.defaultNoOverride, true);
		assert.equal(merged.rules?.[0]?.name, "built-in");
	});
});
